version: '3.9'
services:
  backend:
    build: .
    ports:
    - 8000:8000
    volumes:
    - .:/app
    depends_on:
     - db

  db:
    container_name: ambassador
    image: postgres:14.1
    restart: always
    environment:
      - POSTGRES_USER=ambassador
      - POSTGRES_PASSWORD=pleasechangeme
      - POSTGRES_DB=ambassador
    ports:
      - 5433:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
